In [ ]:
import pandas as pd

In [ ]:
data = {
    "Tid": [1,2,3,4,5,6,7,8,9,10],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status": [
        "Single","Married","Single","Married","Divorced",
        "Married","Divorced","Single","Married","Single"
    ],
    "Taxable Income": [
        "125K","100K","70K","120K","95K",
        "60K","220K","85K","75K","90K"
    ],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

df = pd.DataFrame(data)

df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [ ]:
print(df.iloc[[0, 4, 7, 8]])

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [ ]:
print(df.loc[3:7])

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [ ]:
print(df.iloc[3:8])

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [ ]:
print(df.loc[4:8, 'Refund':'Taxable Income'])

  Refund Marital Status Taxable Income
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K

In [ ]:
print(df.iloc[ :,1:4])

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [ ]:
print(df.loc[:,df.columns[1:4]])

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [ ]:
from google.colab import files
uploaded = files.upload()
print(uploaded)

Saving iris.dataset.csv to iris.dataset (1).csv
{'iris.dataset (1).csv': b'Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\r\n1,5.1,3.5,1.4,0.2,Iris-setosa\r\n2,4.9,3,1.4,0.2,Iris-setosa\r\n3,4.7,3.2,1.3,0.2,Iris-setosa\r\n4,4.6,3.1,1.5,0.2,Iris-setosa\r\n5,5,3.6,1.4,0.2,Iris-setosa\r\n6,5.4,3.9,1.7,0.4,Iris-setosa\r\n7,4.6,3.4,1.4,0.3,Iris-setosa\r\n8,5,3.4,1.5,0.2,Iris-setosa\r\n9,4.4,2.9,1.4,0.2,Iris-setosa\r\n10,4.9,3.1,1.5,0.1,Iris-setosa\r\n11,5.4,3.7,1.5,0.2,Iris-setosa\r\n12,4.8,3.4,1.6,0.2,Iris-setosa\r\n13,4.8,3,1.4,0.1,Iris-setosa\r\n14,4.3,3,1.1,0.1,Iris-setosa\r\n15,5.8,4,1.2,0.2,Iris-setosa\r\n16,5.7,4.4,1.5,0.4,Iris-setosa\r\n17,5.4,3.9,1.3,0.4,Iris-setosa\r\n18,5.1,3.5,1.4,0.3,Iris-setosa\r\n19,5.7,3.8,1.7,0.3,Iris-setosa\r\n20,5.1,3.8,1.5,0.3,Iris-setosa\r\n21,5.4,3.4,1.7,0.2,Iris-setosa\r\n22,5.1,3.7,1.5,0.4,Iris-setosa\r\n23,4.6,3.6,1,0.2,Iris-setosa\r\n24,5.1,3.3,1.7,0.5,Iris-setosa\r\n25,4.8,3.4,1.9,0.2,Iris-setosa\r\n26,5,3,1.6,0.2,Iris-setosa\r\n27,5,3.4,1.6,0.4,Iris-setosa\r\n28,5.2,3.5,1.5,0.2,Iris-setosa\r\n29,5.2,3.4,1.4,0.2,Iris-setosa\r\n30,4.7,3.2,1.6,0.2,Iris-setosa\r\n31,4.8,3.1,1.6,0.2,Iris-setosa\r\n32,5.4,3.4,1.5,0.4,Iris-setosa\r\n33,5.2,4.1,1.5,0.1,Iris-setosa\r\n34,5.5,4.2,1.4,0.2,Iris-setosa\r\n35,4.9,3.1,1.5,0.1,Iris-setosa\r\n36,5,3.2,1.2,0.2,Iris-setosa\r\n37,5.5,3.5,1.3,0.2,Iris-setosa\r\n38,4.9,3.1,1.5,0.1,Iris-setosa\r\n39,4.4,3,1.3,0.2,Iris-setosa\r\n40,5.1,3.4,1.5,0.2,Iris-setosa\r\n41,5,3.5,1.3,0.3,Iris-setosa\r\n42,4.5,2.3,1.3,0.3,Iris-setosa\r\n43,4.4,3.2,1.3,0.2,Iris-setosa\r\n44,5,3.5,1.6,0.6,Iris-setosa\r\n45,5.1,3.8,1.9,0.4,Iris-setosa\r\n46,4.8,3,1.4,0.3,Iris-setosa\r\n47,5.1,3.8,1.6,0.2,Iris-setosa\r\n48,4.6,3.2,1.4,0.2,Iris-setosa\r\n49,5.3,3.7,1.5,0.2,Iris-setosa\r\n50,5,3.3,1.4,0.2,Iris-setosa\r\n51,7,3.2,4.7,1.4,Iris-versicolor\r\n52,6.4,3.2,4.5,1.5,Iris-versicolor\r\n53,6.9,3.1,4.9,1.5,Iris-versicolor\r\n54,5.5,2.3,4,1.3,Iris-versicolor\r\n55,6.5,2.8,4.6,1.5,Iris-versicolor\r\n56,5.7,2.8,4.5,1.3,Iris-versicolor\r\n57,6.3,3.3,4.7,1.6,Iris-versicolor\r\n58,4.9,2.4,3.3,1,Iris-versicolor\r\n59,6.6,2.9,4.6,1.3,Iris-versicolor\r\n60,5.2,2.7,3.9,1.4,Iris-versicolor\r\n61,5,2,3.5,1,Iris-versicolor\r\n62,5.9,3,4.2,1.5,Iris-versicolor\r\n63,6,2.2,4,1,Iris-versicolor\r\n64,6.1,2.9,4.7,1.4,Iris-versicolor\r\n65,5.6,2.9,3.6,1.3,Iris-versicolor\r\n66,6.7,3.1,4.4,1.4,Iris-versicolor\r\n67,5.6,3,4.5,1.5,Iris-versicolor\r\n68,5.8,2.7,4.1,1,Iris-versicolor\r\n69,6.2,2.2,4.5,1.5,Iris-versicolor\r\n70,5.6,2.5,3.9,1.1,Iris-versicolor\r\n71,5.9,3.2,4.8,1.8,Iris-versicolor\r\n72,6.1,2.8,4,1.3,Iris-versicolor\r\n73,6.3,2.5,4.9,1.5,Iris-versicolor\r\n74,6.1,2.8,4.7,1.2,Iris-versicolor\r\n75,6.4,2.9,4.3,1.3,Iris-versicolor\r\n76,6.6,3,4.4,1.4,Iris-versicolor\r\n77,6.8,2.8,4.8,1.4,Iris-versicolor\r\n78,6.7,3,5,1.7,Iris-versicolor\r\n79,6,2.9,4.5,1.5,Iris-versicolor\r\n80,5.7,2.6,3.5,1,Iris-versicolor\r\n81,5.5,2.4,3.8,1.1,Iris-versicolor\r\n82,5.5,2.4,3.7,1,Iris-versicolor\r\n83,5.8,2.7,3.9,1.2,Iris-versicolor\r\n84,6,2.7,5.1,1.6,Iris-versicolor\r\n85,5.4,3,4.5,1.5,Iris-versicolor\r\n86,6,3.4,4.5,1.6,Iris-versicolor\r\n87,6.7,3.1,4.7,1.5,Iris-versicolor\r\n88,6.3,2.3,4.4,1.3,Iris-versicolor\r\n89,5.6,3,4.1,1.3,Iris-versicolor\r\n90,5.5,2.5,4,1.3,Iris-versicolor\r\n91,5.5,2.6,4.4,1.2,Iris-versicolor\r\n92,6.1,3,4.6,1.4,Iris-versicolor\r\n93,5.8,2.6,4,1.2,Iris-versicolor\r\n94,5,2.3,3.3,1,Iris-versicolor\r\n95,5.6,2.7,4.2,1.3,Iris-versicolor\r\n96,5.7,3,4.2,1.2,Iris-versicolor\r\n97,5.7,2.9,4.2,1.3,Iris-versicolor\r\n98,6.2,2.9,4.3,1.3,Iris-versicolor\r\n99,5.1,2.5,3,1.1,Iris-versicolor\r\n100,5.7,2.8,4.1,1.3,Iris-versicolor\r\n101,6.3,3.3,6,2.5,Iris-virginica\r\n102,5.8,2.7,5.1,1.9,Iris-virginica\r\n103,7.1,3,5.9,2.1,Iris-virginica\r\n104,6.3,2.9,5.6,1.8,Iris-virginica\r\n105,6.5,3,5.8,2.2,Iris-virginica\r\n106,7.6,3,6.6,2.1,Iris-virginica\r\n107,4.9,2.5,4.5,1.7,Iris-virginica\r\n108,7.3,2.9,6.3,1.8,Iris-virginica\r\n109,6.7,2.5,5.8,1.8,Iris-virginica\r\n110,7.2,3.6,6.1,2.5,Iris-virginica\r\n111,6.5,3.2,5.1,2,Iris-virginica\r\n112,6.4,2.7,5.3,1.9,Iris-virginica\r\n113,6.8,3,5.5,2.1,Iris-virginica\r\n114,5.7,2.5,5,2,Iris-virginica\r\n115,5.8,2.8,5.1,2.4,Iris-virginica\r\n116,6.4,3.2,5.3,2.3,Iris-virginica\r\n117,6.5,3,5.5,1.8,Iris-virginica\r\n118,7.7,3.8,6.7,2.2,Iris-virginica\r\n119,7.7,2.6,6.9,2.3,Iris-virginica\r\n120,6,2.2,5,1.5,Iris-virginica\r\n121,6.9,3.2,5.7,2.3,Iris-virginica\r\n122,5.6,2.8,4.9,2,Iris-virginica\r\n123,7.7,2.8,6.7,2,Iris-virginica\r\n124,6.3,2.7,4.9,1.8,Iris-virginica\r\n125,6.7,3.3,5.7,2.1,Iris-virginica\r\n126,7.2,3.2,6,1.8,Iris-virginica\r\n127,6.2,2.8,4.8,1.8,Iris-virginica\r\n128,6.1,3,4.9,1.8,Iris-virginica\r\n129,6.4,2.8,5.6,2.1,Iris-virginica\r\n130,7.2,3,5.8,1.6,Iris-virginica\r\n131,7.4,2.8,6.1,1.9,Iris-virginica\r\n132,7.9,3.8,6.4,2,Iris-virginica\r\n133,6.4,2.8,5.6,2.2,Iris-virginica\r\n134,6.3,2.8,5.1,1.5,Iris-virginica\r\n135,6.1,2.6,5.6,1.4,Iris-virginica\r\n136,7.7,3,6.1,2.3,Iris-virginica\r\n137,6.3,3.4,5.6,2.4,Iris-virginica\r\n138,6.4,3.1,5.5,1.8,Iris-virginica\r\n139,6,3,4.8,1.8,Iris-virginica\r\n140,6.9,3.1,5.4,2.1,Iris-virginica\r\n141,6.7,3.1,5.6,2.4,Iris-virginica\r\n142,6.9,3.1,5.1,2.3,Iris-virginica\r\n143,5.8,2.7,5.1,1.9,Iris-virginica\r\n144,6.8,3.2,5.9,2.3,Iris-virginica\r\n145,6.7,3.3,5.7,2.5,Iris-virginica\r\n146,6.7,3,5.2,2.3,Iris-virginica\r\n147,6.3,2.5,5,1.9,Iris-virginica\r\n148,6.5,3,5.2,2,Iris-virginica\r\n149,6.2,3.4,5.4,2.3,Iris-virginica\r\n150,5.9,3,5.1,1.8,Iris-virginica\r\n'}

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("iris.dataset.csv")

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.drop(index=4,axis=0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.drop(columns="SepalWidthCm", inplace=True)

In [ ]:
df

      Id  SepalLengthCm         Species
0      1            5.1     Iris-setosa
1      2            4.9     Iris-setosa
2      3            4.7     Iris-setosa
3      4            4.6     Iris-setosa
4      5            5.0     Iris-setosa
..   ...            ...             ...
145  146            6.7  Iris-virginica
146  147            6.3  Iris-virginica
147  148            6.5  Iris-virginica
148  149            6.2  Iris-virginica
149  150            5.9  Iris-virginica

[150 rows x 3 columns]